# Red Pitaya TDC port mapping only!
# Clock constraints generated by BD
#
# Michel Adamic, 11.6.2019
# 13.6.2019 -> added test ports
# 28.6.2019 -> 2 channels
# 18.9.2019 -> M14, M15 (Red Pitaya 10)
# 8.11.2019 -> Carry chain placement constraints
# 13.11.2019 -> 4-bit test ports
# 2.8.2020 -> testUnit is replaced with a constant output

# TDC inputs
#set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports hit0]
#set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports hit1]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports hit0]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports hit1]

# Test ports
#set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports testOut[0]]
#set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports testOut[1]]
#set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports testOut[2]]
#set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports testOut[3]]

set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports LEDout[0]]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports LEDout[1]]
#set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports testLED[2]]
#set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports testLED[3]]

# Carry chain beginning
#set_property LOC SLICE_X2Y25 [get_cells TDCsystem_i/AXITDC_0/U0/TDC/Delay_line/firstCarry]
#set_property LOC SLICE_X17Y25 [get_cells TDCsystem_i/AXITDC_1/U0/TDC/Delay_line/firstCarry]